### ISSUE TITLE
Update to latest appdata / metainfo standards

### ISSUE THREAD

**Issue by tchx84** [tchx84/sugarapp#14]
See https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/ and run the following 

```
flatpak run --command=flatpak-builder-lint org.flatpak.Builder appstream ~/.local/share/flatpak/app/org.sugarlabs.Pippy/current/active/files/share/appdata/org.sugarlabs.Pippy.appdata.xml
```

We get

```
I: org.sugarlabs.Pippy:5: developer-name-tag-deprecated
   The toplevel `developer_name` element is deprecated. Please use the `name` element in a
   `developer` block instead.

I: org.sugarlabs.Pippy:~: developer-info-missing
   This component contains no `developer` element with information about its author.

✔ Validation was successful: infos: 2, pedantic: 4
```

**Comment by hackorlyf** [comment]
I am interested in exploring this.

**Comment by tchx84** [comment]
> I am interested in exploring this.

Thanks, let me know if there's any question.

**Comment by SudoSu-bham** [comment]
Thank-you for feedback and review of my commit on BaseApp.  Here are some additional details and questions regarding the metainfo.
I attempted to execute the above command, but encountered issues due to its legacy path and filename. Instead, I used the following command 
`flatpak run --command=flatpak-builder-lint org.flatpak.Builder appstream ~/.local/share/flatpak/app/org.sugarlabs.Pippy/current/active/files/share/metainfo/org.sugarlabs.Pippy.metainfo.xml`
The output yielded similar results to yours, the area where we can do improvements are listed below.

1.  **Fixing infos: 2**

Is `Sugar Labs Community` or `your account` verified as developer on flathub, if yes than what is developer's ID we will have to write it in the id property . We can consider this documentation for [developer verification](https://docs.flathub.org/docs/for-app-authors/verification)
The new developer block will look like this
```
<developer id="tld.domain"> 
    <name> Sugar Labs Community </name> 
</developer>
```

2. **Fixing pedantic: 4:**

-  The `<id>org.sugarlabs.Pippy</id>` element generates a pedantic error. According to [metainfo guidelines](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/) we should use lowercase alphabets for the `<id></id>` element.
The modified version will look like this
```
<id>org.sugarlabs.pippy</id>
<replaces>
  <id>org.sugarlabs.Pippy</id>
</replaces>
```
should we change the id or continue with older one?

-  Additionally, other three pedantic errors were caused by the lack of `<caption> </caption>` elements for each screenshot, as per [metainfo guidelines](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/).
I have used some captions for the images are they good?
```
<screenshots>
    <screenshot type="default">
        <image>https://i.imgur.com/VeZWL2q.png</image>
        <caption>Pippy IDE</caption>
    </screenshot>
    <screenshot>
        <image>https://i.imgur.com/7QOhdmS.png</image>
        <caption>Physics example</caption>
    </screenshot>
    <screenshot>
        <image>https://i.imgur.com/fNlsMcf.png</image>
        <caption>Pong example</caption>
    </screenshot>
</screenshots>
```

Thank you for your assistance. Please let me know if you require any additional information or have further suggestions.

**Comment by tchx84** [comment]
Let's start by fixing the developer name, we don't need to solve everything at once.

It should be something like this:

```
<developer id="org.sugarlabs"> 
    <name>Sugar Labs Community</name> 
</developer>
```

Re. the other topics:

* Any developer associated to our apps can do the verification step (e.g., me) and it will require exposing a file ` https://sugarlabs.org/.well-known/org.flathub.VerifiedApps.txt` we can ask help from SL systems team.
* Let's not change the app ids for now.
* We can address the caption issue later, as it requires adding a new "custom" field to the `activity.info`.

**Comment by SudoSu-bham** [comment]
Should we hard code `developer id`?
Also we can utilize [activity.info](https://github.com/flathub/org.sugarlabs.Pippy/blob/master/pippy-info.patch), either we can extract  `id`  from `bundle_id` which contains `org.sugarlabs.Pippy` or we may need to include a `dev_id=org.sugarlabs` attribute in `activity.info`. Which one is more appropriate?

**Comment by tchx84** [comment]
> Should we hard code `developer id`? Also we can utilize [activity.info](https://github.com/flathub/org.sugarlabs.Pippy/blob/master/pippy-info.patch), either we can extract `id` from `bundle_id` which contains `org.sugarlabs.Pippy` or we may need to include a `dev_id=org.sugarlabs` attribute in `activity.info`. Which one is more appropriate?

Good point, a new field is the proper approach (I guess no escape from adding more fields.)
